import { createApp } from "vue";
import { createPinia } from "pinia";
import ArcoVue from "@arco-design/web-vue";
import ArcoVueIcon from "@arco-design/web-vue/es/icon";
import Particles from "vue3-particles";
import router from "./router";
import App from "./App.vue";
import "highlight.js/styles/agate.css";
import "@arco-design/web-vue/dist/arco.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "prismjs/themes/prism.css";
const app = createApp(App);
app.use(ArcoVue);
app.use(ArcoVueIcon);
app.use(createPinia());
app.use(Particles);
app.use(router);
app.mount("#app");
